# This will deploy the safe / secure / tested app to prod server
name: Deploy to Server
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH to prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Starting Deployment"
            mkdir -p devops

      - name: Copy the docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ~/devops

      - name: SSH to Prod server & run the app
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          script: |
            echo "Running App"
            sudo apt-get install docker.io docker-compose-v2 -y
            sudo usermod -aG docker $USER && newgrp docker
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
            export DOCKER_TAG=${{ github.sha }}
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always
