# uses Trivy image scanner for CVEs
name: Image Scanner
on:
  workflow_call:

jobs:
  image-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USER }}/github-actions-zero-to-hero:${{ github.sha }}
          severity: 'CRITICAL'
          ignore-unfixed: true
          exit-code: '1'
