---
name: Job Output Workflow

on:
  # push:
  workflow_dispatch:
  
jobs:
  get-date:
    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.date_step.outputs.today }}

    steps:
      - id: date_step
        run: echo "today=$(date)" >> $GITHUB_OUTPUT

  print-date:
    runs-on: ubuntu-latest
    needs: get-date

    steps:
      - name: Show date
        run: echo "Date is ${{ needs.get-date.outputs.today }}"
