---
name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter environment"
        required: true
        default: "staging"

jobs:
  manual-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print input
        run: echo "Environment is ${{ github.event.inputs.environment }}"
