---
name: Matrix Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version  }}

      - name: show version
        run: python --version
